# Arquivo de configuração para definir o cluster Kubernetes com Kind

kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
- role: control-plane
- role: worker
- role: worker

    # Realizando port-forward do IP da minha máquina em vez de acessar aplicação com IP do container
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8080  